all:
  children:
    test_group:
      hosts:
        host1:
          ansible_host: 127.0.0.1
          ansible_connection: local
        host2:
          ansible_host: 127.0.0.2
          ansible_connection: local
    another_group:
      hosts:
        host3:
          ansible_host: 127.0.0.3
          ansible_connection: local
